package fables.kotlin.jee.idiomatic.business

import fables.kotlin.jee.idiomatic.Kitten
import javax.persistence.*

/**
 * Class and all public methods are opened by Kotlin compiler "allopen" plugin.
 * Parameterless constructor generated by Kotlin compiler "jpa" plugin.
 * @author Zeljko Trogrlic
 */
@SequenceGenerator(name = "kittens_id_seq", sequenceName = "kittens_id_seq", allocationSize = 1)
@Entity
@Table(name = "kittens")
data class KittenEntity private constructor(
        @Id
        @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "kittens_id_seq")
        var id: Int?,
        override var name: String,
        override var cuteness: Int // set Int.MAX_VALUE for Nermal
) : Kitten {

    constructor(name: String, cuteness: Int) : this(null, name, cuteness)
}