package fables.kotlin.jee.business

import fables.kotlin.jee.Kitten
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.Id

/**
 * Persistent kitten.
 * Class and all public methods are opened by Kotlin compiler "allopen" plugin.
 * Parameterless constructor generated by Kotlin compiler "jpa" plugin.
 * @author Zeljko Trogrlic
 */
@Entity
data class KittenEntity private constructor(
        @Id
        @GeneratedValue
        var id: Int?,
        override var name: String,
        override var cuteness: Int // set Int.MAX_VALUE for Nermal
) : Kitten {

    constructor(name: String, cuteness: Int) : this(null, name, cuteness)
}
